DEBUG_MODE = false

SCREEN_WIDTH = 128
SCREEN_HEIGHT = 128

DEFAULT_SCALE = 5

TILE_SIZE = 8
SCREEN_TILES_WIDTH = 16
SCREEN_TILES_HEIGHT = 16

CAMERA_LOW_HEIGHT = 80
CAMERA_HIGH_HEIGHT = 50

PLAYER_WIDTH = 7
PLAYER_HEIGHT = 7

PLAYER_MAX_RUN_VEL = 0.75
PLAYER_RUN_ACCEL = 0.13
PLAYER_RUN_DECEL = 0.13

PLAYER_MAX_AIR_VEL = 1
PLAYER_AIR_ACCEL = 0.13
PLAYER_AIR_DECEL = 0.03

PLAYER_MAX_CLIMB_VEL = 0.4
PLAYER_CLIMB_ACCEL = 0.5
PLAYER_CLIMB_DECEL = 0.5
PLAYER_SLIDE_GRAV = 0.03

PLAYER_CLIMBUP_VEL = 1.2
PLAYER_JUMP_VEL = 1.2
PLAYER_CLIMB_JUMP_VEL_Y = 1.168
PLAYER_CLIMB_JUMP_VEL_X = 1.7

PLAYER_CLIMB_WARNING = 60
PLAYER_CLIMB_TIME = 115
PLAYER_CLIMB_INCREASE = 1
PLAYER_GRAB_INCREASE = 0.25
PLAYER_CLIMB_BLINK = 20

PLAYER_GRAVITY_ACCEL = 0.15

PLAYER_BOUNCE_FALLOFF = 0.7
PLAYER_BOUNCE_THRESHOLD = 1.5

PLAYER_MANTLE_FRAMES = 10

COYOTE_TIME_GROUND = 6
COYOTE_TIME_WALL = 6
PLAYER_DISCONNECT_FRAMES = 10

PLAYER_DRAW_WIDTH = 8
PLAYER_DRAW_HEIGHT = 9
PLAYER_SPRITE_ROWS = 8
PLAYER_SPRITE_COLS = 5
PLAYER_BOUNCE_FRAMES = 5

WALL_SPRITE_ROWS = 1
WALL_SPRITE_COLS = 4