SCREEN_WIDTH = 128
SCREEN_HEIGHT = 128

DEFAULT_SCALE = 5

TILE_SIZE = 8

PLAYER_MAX_RUN_VEL = 1
PLAYER_RUN_ACCEL = 0.1
PLAYER_RUN_DECEL = 0.15
PLAYER_MAX_CLIMB_SPEED = 0.5
PLAYER_CLIMB_ACCEL = 0.1
PLAYER_CLIMB_DECEL = 0.1
PLAYER_JUMP_VEL = -2
PLAYER_CLIMB_JUMP_VEL_Y = -2
PLAYER_CLIMB_JUMP_VEL_X = 3
PLAYER_GRAVITY_ACCEL = 0.2
PLAYER_WIDTH = 8
PLAYER_HEIGHT = 8